# Generated by Django 5.2.6 on 2026-01-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_companyinfo_heroslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
