# Generated by Django 5.2.6 on 2026-01-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_heroslide_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='company_assets/'),
        ),
    ]
