# Generated by Django 5.2.6 on 2026-01-10 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_sellingpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='icon_name',
        ),
    ]
