# Generated by Django 5.2.6 on 2026-01-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_advertisement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='map_image',
            field=models.ImageField(blank=True, help_text='Fallback image if interactive map is not used', null=True, upload_to='company_assets/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='map_url',
            field=models.URLField(blank=True, help_text='Link to Google Maps or similar'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='opening_hours',
            field=models.TextField(blank=True, help_text='Line separated opening hours'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='payment_image',
            field=models.ImageField(blank=True, help_text='Payment methods icons image', null=True, upload_to='company_assets/'),
        ),
    ]
