# Generated by Django 5.2.6 on 2026-01-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_companyinfo_map_image_companyinfo_map_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopage',
            name='content',
            field=models.TextField(help_text='Flexible JSON content for sections'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
